version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=FS_APP
    volumes:
      - ./docker_data:/data/db
    ports:      
      - 5432:5432
